---
- name: Download k3s binary
  become: yes
  get_url:
    url: "https://github.com/rancher/k3s/releases/download/v1.17.4%2Bk3s1/k3s"
    dest: /usr/local/bin/k3s
    mode: +x
- name: Upload service file
  become: yes
  copy:
    src: files/k3s/k3s.service
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: '0644'
- name: Enable k3s server
  become: yes
  systemd:
    name: k3s
    daemon_reload: yes
    state: started
    enabled: yes
